### ISSUE TITLE
About Obpsy

### ISSUE THREAD

**Issue by CristianQ1** [speedshi/MALMI#3]

**Comment by CristianQ1** [comment]
dear Shi,When I get tested and run the "run_MALMI.py",it appeared that something wrong about obspy and datatime.Lack the  parameter "month".Where can I get this  parameter please?

**Comment by speedshi** [comment]
Can you provide more information on how to run the code?
Did you run the script on the test dataset provided in the "tests" folder in the repo?
What are the error messages (better paste the error massages here as well)

**Comment by CristianQ1** [comment]
Thanks shi,The error is shown like that:

Traceback (most recent call last):
  File "run_MALMI.py", line 13, in <module>
    from main import MALMI
  File "/home/qiut/EQTransformer/MALMI/src/main.py", line 21, in <module>
    import obspy
  File "/home/qiut/anaconda3/envs/MALMI/lib/python3.7/site-packages/obspy/__init__.py", line 34, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/qiut/anaconda3/envs/MALMI/lib/python3.7/site-packages/obspy/core/__init__.py", line 122, in <module>
    from obspy.core.trace import Stats, Trace  # NOQA
  File "/home/qiut/anaconda3/envs/MALMI/lib/python3.7/site-packages/obspy/core/trace.py", line 29, in <module>
    class Stats(AttribDict):
  File "/home/qiut/anaconda3/envs/MALMI/lib/python3.7/site-packages/obspy/core/trace.py", line 150, in Stats
    'starttime': UTCDateTime(0),
  File "/home/qiut/anaconda3/envs/MALMI/lib/python3.7/site-packages/obspy/core/utcdatetime.py", line 451, in __init__
    dt = datetime.datetime(*args, **kwargs)
TypeError: function missing required argument 'month' (pos 2)

I have installed obspy==1.3.1,maybe the version is the issue?Do you have the most recommend version?

**Comment by speedshi** [comment]
It seems this error occurs when import obspy
I would suggest updating the obspy installation of the used virtual environment to the latest version.

**Comment by CristianQ1** [comment]
deer shi,


The obpsy version is 1.3.1,the latest one for python3.7.


Python3.7 is the version that Github requires.


So could this problem occurs by something else?


yours,toy.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "speedshi/MALMI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月3日(星期一) 下午4:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [speedshi/MALMI] About Obpsy (Issue #3)





 
It seems this error occurs when import obspy
 I would suggest updating the obspy installation of the used virtual environment to the latest version.

**Comment by speedshi** [comment]
It is okay to update Python to version 3.9.
If not possible I would suggest creating a new virtual environment, for example:
conda create -n malmi python=3.9
Install seisbench as the ML engine in the virtual environment, by using: 
pip install seisbench

Then following the manual to install other required packages in the virtual environment, (LOKI, NonLinLoc etc)
